name: Rust

on:
  push:
    branches: [ "main", "lf" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Check formatting
      run: cargo fmt --check
    - name: Build
      run: cargo build
    - name: Check docs
      run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps
    - name: Run tests
      run: cargo test --all-features
  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install cargo-fuzz
      run: cargo +nightly install cargo-fuzz
    - name: Run crlf fuzz tests
      run: cargo +nightly fuzz run --release crlf -- -runs=1000000
    - name: Run lf fuzz tests
      run: cargo +nightly fuzz run --release lf -- -runs=1000000
